### ISSUE TITLE
Inject vault secrets additionally in JSON format

### ISSUE THREAD

**Issue by brendangadd** [StatCan/kubeflow-controller#7]
Vault secrets are currently injected as a source-able shell script, which is ultra convenient when working in a shell. For programmatic access to secrets, it would be nice to have something easier to parse outside a shell.

Can we add an extra `.json` file (alongside the shell scripts) that can be used from applications?

https://github.com/StatCan/kubeflow-controller/blob/master/defaults.go

**Comment by sylus** [comment]
We're thinking of using the INI file format instance, then it will work with a `source` call as well as being easily readable from code (ex: https://stackoverflow.com/questions/8884188/how-to-read-and-write-ini-file-with-python3)

**Comment by justbert** [comment]
Where modifications need to be done:
[defaults.go](https://github.com/StatCan/kubeflow-controller/blob/master/defaults.go)

**Comment by frazs** [comment]
Since https://github.com/StatCan/daaas/issues/86 is in progress, I think what makes sense here is:

1. Finish https://github.com/StatCan/daaas/issues/86 
2. Swap out the injector's payload from the shell script to the INI format
3. Once functionality of the new format is confirmed, remove the configuration

**Comment by frazs** [comment]
Per today's stand-up, Brendan still wants JSON. Do we go JSON+INI, JSON+bash script, or JSON+INI+bash script?

**Comment by frazs** [comment]
If we're going e.g. JSON+bash script, is adding additional annotations (`vault.hashicorp.com/agent-inject-template-json-minio-[minimal/pachyderm/premium]-tenant1` sufficient, or must something be configured to accept them? I am not sure, currently, how the template in the annotations is translated to a file in the notebook.

**Comment by blairdrummond** [comment]
I think it really is as easy as adding the annotation. This is an old chart that I used, but you can probably adapt it to just run `sleep 600` on alpine to test out the injection!

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-{{ .Values.experiment.sha }}-{{ .Values.experiment.type }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      annotations:
        minio-profile: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-pre-populate: "false"
        # vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-minio-minimal-tenant1: minio_minimal_tenant1/keys/profile-{{ .Values.namespace }}
        vault.hashicorp.com/role: profile-{{ .Values.namespace }}
        vault.hashicorp.com/agent-inject-template-minio-minimal-tenant1: |
          {{ "{{-" }} with secret "minio_minimal_tenant1/keys/profile-{{ .Values.namespace }}" {{ "}}" }}
          export MINIO_URL="http://minimal-tenant1-minio.minio:9000"
          export MINIO_ACCESS_KEY="{{ "{{" }} .Data.accessKeyId {{ "}}" }}"
          export MINIO_SECRET_KEY="{{ "{{" }} .Data.secretAccessKey {{ "}}" }}"
          {{ "{{-" }} end {{ "}}" }}
        vault.hashicorp.com/agent-inject-command-minio-minimal-tenant1: "kill 1"

    spec:
      containers:
      - name: covid-rl-agents
        image: k8scc01covidacr.azurecr.io/covid-rl-agents:{{ .Values.covidimage.agents }}
        resources:
          limits:
            cpu: {{ .Values.cpu.limit }}
            memory: {{ .Values.memory.limit }}
          requests:
            cpu: {{ .Values.cpu.request }}
            memory: {{ .Values.memory.request }}
        env:
          - name: NUMBA_NUM_THREADS
            value: "{{ .Values.cpu.request }}"
        command: ["/bin/bash", "-c"]
        args:
        - |
           set -e;
           for i in `seq 12`; do [ -s /vault/secrets/minio-minimal-tenant1 ] && break || { echo "Waiting for sidecar."; sleep 5; }; done;
           source /vault/secrets/minio-minimal-tenant1;
           mc config host add datastore ${MINIO_URL} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
           echo "Secrets mounted.";
           echo python3 ./runit.py {{- range $key, $val := .Values.parameters }} {{ $val.flag }} {{ $val.value }} {{- end }} | tee COMMAND;
           sh ./scripts/run-with-profiling.sh {{- range $key, $val := .Values.parameters }} {{ $val.flag }} {{ $val.value }} {{- end }};
           rm -rf __pycache__;
           mc cp -r . datastore/shared/{{ .Values.namespace }}/covid-rl/{{ .Values.covidimage.agents }}-${POD_NAME}/;
           echo "Kill the istio proxy.";
           curl -X POST http://localhost:15020/quitquitquit;
           exit 0;
      imagePullSecrets:
          - name: image-pull-secret      
      restartPolicy: Never
  backoffLimit: 1
```
